function [output, act_h, act_a] = Forward(W, b, X)
% [OUT, act_h, act_a] = Forward(W, b, X) performs forward propogation on the
% input data 'X' uisng the network defined by weights and biases 'W' and 'b'
% (as generated by InitializeNetwork(..)).
% This function should return the final softmax output layer activations in OUT,
% as well as the hidden layer pre activations in 'act_a', and the hidden layer post
% activations in 'act_h'.
X = X';
% for i = 1:numel(W)
n = size(W{1,1},1);
X = repmat(X,n);
act_a = dot(W{1,1},X,2)+b{1,1};
act_h = 1./(1+exp(-nw));
output = dot(W{1,2},act_h,2)+b{1,2};
% exp_nw = exp(nw);
% probabilities = exp_nw/sum(exp_nw);
%     Li = -log10(probabilities);
% end
